# 简单的测试任务集
tasks:
  - name: Task_High
    type: sporadic
    period: 100
    wcet: 10
    priority: 1
    workload: bzip2

  - name: Task_Mid
    type: sporadic
    period: 200
    wcet: 15
    priority: 2
    workload: hash

  - name: Task_Low
    type: sporadic
    period: 300
    wcet: 20
    priority: 3
    workload: control
