taskset:
  - name: task_1
    iat: 50
    runtime: 10
    deadline: 40
    offset: 0
    params: "period=50,wcet=10,arrival_offset=0,workload=bzip2"
    code:
      - fixed(10, bzip2)

  - name: task_2
    iat: 100
    runtime: 20
    deadline: 80
    offset: 0
    params: "period=100,wcet=20,arrival_offset=0,workload=hash"
    code:
      - fixed(20, hash)

  - name: task_3
    iat: 150
    runtime: 25
    deadline: 120
    offset: 0
    params: "period=150,wcet=25,arrival_offset=0,workload=encrypt"
    code:
      - fixed(25, encrypt)
